#!/usr/bin/env bash

docker pull "moddengine/moddengine:udo20-latest"

UPGRADE_LIST=$(
  whiptail \
    --title "Udo20 Container to upgrade" \
    --separate-output \
    --checklist "Select Container" 20 90 14 \
    $(docker ps -a --format "{{ .Names }} {{ .Image }} OFF" --filter label=au.net.udo.ver=udo20) \
    3>&1 1>&2 2>&3
)

if [[ -z "$UPGRADE_LIST" ]]; then
  echo "Nothing selected"
  echo "'$UPGRADE_LIST'";
  exit 1
fi

for UPGRADE_NAME in $UPGRADE_LIST; do
  echo Upgrade: $UPGRADE_NAME
  UDO_USER=$(echo "$UPGRADE_NAME" | cut -f1 -d_)
  UDO_SITE=$(echo "$UPGRADE_NAME" | cut -f2 -d_)

  ./start-udo "$UDO_USER" -s "$UDO_SITE"
  sleep 15
done

